# Encoding: utf-8
#
# Problem:
# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
#   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not
# exceed four million, find the sum of the even-valued terms.
#
# http://projecteuler.net/problem=2
#
# Author: Harsh Sinha
# Date June 9, 2013

total = 0
prev_fib_num = 1
current_fib_num = 2

while current_fib_num < 4_000_000
    if current_fib_num % 2 == 0
        total += current_fib_num
        # print "#{current_fib_num}, #{total}\n"
    end

    print "#{current_fib_num}, #{total}\n"

    next_num = current_fib_num + prev_fib_num
    prev_fib_num = current_fib_num
    current_fib_num = next_num
end
